### ISSUE TITLE
I can't find console here

### ISSUE THREAD

**Issue by PlutoCA** [storybookjs/storybook-addon-console#10]
`
    "react": "^16.8.6",
"@storybook/addon-actions": "^5.0.10",
    "@storybook/addon-console": "^1.1.0",
    "@storybook/addon-info": "^5.0.10",
    "@storybook/addon-links": "^5.0.10",
    "@storybook/addon-storysource": "^5.0.10",
    "@storybook/addon-viewport": "^5.0.10",
    "@storybook/addons": "^5.0.10",
    "@storybook/react": "^5.0.10",
    "@types/storybook__react": "^4.0.1",
`

.storybook/config.js
`import '@storybook/addon-console';`

![image](https://user-images.githubusercontent.com/31099607/56783402-2fb1cd80-681e-11e9-96f3-843c440513b2.png)

**Comment by renestalder** [comment]
@PlutoCA Check the readme. it states that the import is added to `config.js` instead of `addons.js`. That was the mistake in my case that the console logs didn't run up.

**Comment by UsulPro** [comment]
answered in #12
