### ISSUE TITLE
Make compatible with addons.js register

### ISSUE THREAD

**Issue by renestalder** [storybookjs/storybook-addon-console#12]
Compared to other addons, this addon is required to be added in the `config.js` as there is no register function. It would be nice it could be applied as every other addon.

**Current setup**

`config.js`:

```js
import '@storybook/addon-console';
```

**Expected setup**

`addons.js`:

```js
import '@storybook/addon-console/register';
```

**Comment by UsulPro** [comment]
Hey @renestalder

**Comment by UsulPro** [comment]
Hey @renestalder 

there are different ways how people can extend Storybook functionality

usually addons add something to `addons.js` when they injects some UI into Storybook interface. But this addon don't have own panel it uses panel of another addon for displaying outputs.

Another addon is `@storybook/addon-actions` which is specified as a Peer Dependency - didn't you notice a warning about missing peer dependency?

This way allows to focus only on the one thing and don't bloat addons panel

So sorry for not clear readme, I expected that users usually have `addon-actions`, but actually I shouldn't rely on that :smile:

**Comment by UsulPro** [comment]
After Storybook v5 got rich UI options it possibly worth to add something to notify users on the manager-side

**Comment by renestalder** [comment]
@UsulPro Thanks for clarification.
