### ISSUE TITLE
compatibility with storybook 5.3? [resolved]

### ISSUE THREAD

**Issue by acroyear** [storybookjs/storybook-addon-console#27]
I had things configured fine for 5.2.8, but when upgrading to 5.3 and moving the reference to the new file format, i get errors on startup.

ERR! Error: Accessing non-existent addons channel, see https://storybook.js.org/basics/faq/#why-is-there-no-addons-channel
ERR!     at AddonStore.getChannel (/Users/joe/Projects/subfirelib/node_modules/@storybook/addons/dist/index.js:45:13)
ERR!     at Object.actionHandler [as log] (/Users/joe/Projects/subfirelib/node_modules/@storybook/addon-actions/dist/preview/action.js:25:34)

**Comment by acroyear** [comment]
This can be closed after a documentation update of the README.md. 

My issue was that I was trying to include it in the plug-ins list in main.js under the new file structure for 5.3. This addon needs to be imported in preview.js (which is what inherited much of config.js) and things are now working again without error.

**Comment by csalvato** [comment]
@acroyear I'm facing the same issue, and I'm wondering what you mean by this, specifically?

>This addon needs to be imported in preview.js (which is what inherited much of config.js) and things are now working again without error.

I removed the file from my `addons` array in `main.js` and am importing what I need in `preview.js` like this

```js
import { setConsoleOptions, withConsole } from '@storybook/addon-console'
```

But the console does not seem to be working. Any advice?

**Comment by acroyear** [comment]
I'm just doing raw `import '@storybook/addon-console';`, no configuration at this point, right at the top of preview.js.

**Comment by csalvato** [comment]
Thanks @acroyear !

**Comment by jeanfredrik** [comment]
I’m getting the same error with Storybook 5.3. Here’s my config:

main.js
```js
module.exports = {
  stories: ["../src/**/*.stories.js"],
  addons: [
    "@storybook/addon-actions",
    "@storybook/addon-a11y",
    "@storybook/addon-console",
    "@storybook/addon-links",
    "@whitespace/storybook-addon-html",
  ],
  // ...
};
```

preview.js
```js
import { addDecorator } from "@storybook/react";
import { withHTML } from "@whitespace/storybook-addon-html/react";
import { withA11y } from "@storybook/addon-a11y";
import "@storybook/addon-console";

addDecorator(withHTML);
addDecorator(withA11y);
```

Any ideas on how to fix it?

**Comment by j-a-y-h** [comment]
@jeanfredrik I was able to get it working by removing `@storybook/addon-console` from the addons array in `main.js`. I believe this works because console uses actions panel to output console messages. Maybe the other addons you have listed there are causing the same issues (ie try removing them as well).

**Comment by boatcoder** [comment]
I'm seeing it log to the actions panel too.  I was expecting an extra panel but it doesn't appear.

**Comment by UsulPro** [comment]
#29
