### ISSUE TITLE
Error logging circular reference

### ISSUE THREAD

**Issue by wfischer42** [storybookjs/storybook-addon-console#28]
I ran into an error console logging an object with a circular reference, which is a limitation of JSON.stringify(). This adds a bit of unwanted overhead in debugging, since I have to turn off the console anytime I need to log circular references, so I'd love to see this worked out. 

Otherwise, this addon has been very helpful. Thanks!

**Comment by UsulPro** [comment]
Hi @wfischer42 possibly this is the problem of `addon-actions` since it's used for displaying logs in actions panel. Could you clarify at what point this error happens?
