### ISSUE TITLE
This doesn't work with console.dir

### ISSUE THREAD

**Issue by nratter** [storybookjs/storybook-addon-console#39]
Nothing is displayed when using console.dir. Can we make it work for this as well?

**Comment by takurinton** [comment]
@ndelangen @usulpro 
Do you think this is necessary?
I can't think of many cases where I would use it myself, but I feel that the need for this itself certainly exists.
If you think it should be implemented I would be willing to start working on this.

**Comment by ndelangen** [comment]
I'd welcome a PR adding the feature.
