### ISSUE TITLE
Support for Storybook 7

### ISSUE THREAD

**Issue by Bowriverstudio** [storybookjs/storybook-addon-console#65]
Is there documentation for using this plugin in Storybook 7?

**Comment by IanVS** [comment]
What error are you seeing?  It looks like this addon was written for 5.x style, which means it probably could use some updates, though it sounds like people had it working in 6.5 by importing it into their `.storybook/preview.js`.  Is that no longer working?  Would you be interested in updating the project to match the newer style of addons?

**Comment by sheriffMoose** [comment]
@IanVS if I may, I implemented the same concepts with v7 in  [@storybook-extras/console](https://github.com/sheriffMoose/storybook-extras/tree/master/packages/console). Please let me know if you would like to consolidate our efforts, either here or there, I am open to all. Thanks.

**Comment by IanVS** [comment]
That's great, @sheriffMoose, thanks for that.  Is your version a drop-in for this one?  I think we could either deprecate this one and point folks to yours, or maybe you'd like to get this version up to snuff?  This one has 100,000 weekly downloads, so maybe it's worth fixing up?  @ndelangen do you have thoughts here?

**Comment by sheriffMoose** [comment]
@IanVS it is not a drop in unfortunately, I developed it initially to be part of the Angular Extras addons, I just moved it to a separate package a few days ago. And the plan is to maintain it long term. Let me know what you prefer. I do not want to disrupt this addon since it is widely used.

**Comment by Bowriverstudio** [comment]
@sheriffMoose  - thank you I'll take a look at that plugin.

@IanVS 
When I include this:  in my preview.js file

```js
import { withConsole } from "@storybook/addon-console";
import { addDecorator } from "@storybook/react";
addDecorator((storyFn, context) => withConsole()(storyFn)(context));
```

I get the warning: Typescript warning:
'"@storybook/react"' has no exported member named 'addDecorator'. Did you mean 'Decorator'?

I believe addDecorator is deperdated in  SB7.
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#dropped-support-for-addon-actions-adddecorators

**Comment by IanVS** [comment]
Based on this comment you just need to import for side-effects: https://github.com/storybookjs/storybook-addon-console/issues/41#issuecomment-809101235

**Comment by dkimmich-onventis** [comment]
In Storybook v7, after importing the plugin in `preview.js` via `import '@storybook/addon-console';`, I'm getting the following runtime error:

```
ERROR in ./node_modules/@storybook/addon-console/dist/index.js 8:37-61
Module not found: Error: Can't resolve 'global/window'
```

**Comment by ndelangen** [comment]
I'd be awesome if someone would be able to upgrade this to use tsup, and bring it up to date with 7.0.

**Comment by takurinton** [comment]
Hello. Thanks again for this great library.

I am interested in this assignment and actually tried to move it around at hand.
I don't know if this contribution is worth it, but for now I can confirm that debugging, build passed and all tests pass using storybook v7 at hand.
https://github.com/takurinton/storybook-addon-console/pull/1

If this is worthwhile, I am ready to create a pull request to this repository.

Can I contribute to this??
