### ISSUE TITLE
[Bug] Can't resolve 'global/window' error after updating to Storybook v7

### ISSUE THREAD

**Issue by dkimmich-onventis** [storybookjs/storybook-addon-console#66]
### Describe the bug

I import the plugin in my `preview.js` with a simple import:

```
import '@storybook/addon-console';
```

It works fine for Storybook v6, but I'm getting an error after updating to v7.

### Expected behavior

The addon works with Storybook v7.

### Screenshots and/or logs

```
ERROR in ./node_modules/@storybook/addon-console/dist/index.js 8:37-61
Module not found: Error: Can't resolve 'global/window'
```

### Environment

 - Storybook version: v7.0.0-rc.7
 - OS: macOS
 - Node.js version: v18.15.0
 - NPM version: v8.19.4
 - Browser (if applicable): Chrome

**Comment by IanVS** [comment]
Can you please create a reproduction?  https://storybook.new/ is an easy way.

**Comment by dkimmich-onventis** [comment]
Reproduction: https://stackblitz.com/edit/github-fbqwza

**Comment by florianRadureau** [comment]
Hello Ian, same here, with angular too :/

**Comment by unional** [comment]
![image](https://user-images.githubusercontent.com/3254987/229946768-69372f5e-a03a-4415-9afe-03906daf5858.png)

The version of `global` I got is 4.4.0,

It somehow exposed a `global` object as `Window`, under `require('global')`.

**Comment by unional** [comment]
That actually comes from `index.js` in  `@storybook/global@5.0.0`

**Comment by dkimmich-onventis** [comment]
@ndelangen Could you create a new release? I'm still unable to use the addon because the fix hasn't been released yet.
