### ISSUE TITLE
Unable to exclude warning, error messages from action logger panel

### ISSUE THREAD

**Issue by brettmcdade** [storybookjs/storybook-addon-console#9]
Hello --

I'm looking for guidance on how I can go about only including console.log messages in the action logger panel.

In my config.js, I have the following:

```
import { setConsoleOptions } from '@storybook/addon-console';
.
.
.
const panelExclude = setConsoleOptions({}).panelExclude;
setConsoleOptions({
  panelExclude: [...panelExclude, /error/, /warn/]
});
```

Currently this still outputs everything to the action logger panel (excluding [HMR])

**Comment by UsulPro** [comment]
duplicate #13

**Comment by 0x0006e** [comment]
same issue
